---
- name: Install git
  package:
    name: 'git'

- name: Clone Ugly-Map repo
  git:
    repo: 'https://{{ um_gitlab_user | urlencode }}:{{ um_gitlab_token }}@gitlab.com/dreamhack/ugly-map.git'
    dest: "{{ um_location }}"
    accept_hostkey: true
    version: master

- name: Template config file
  template:
    src: production.yml.j2
    dest: "{{ um_location }}/config/production.yml"

- name: Build docker image
  docker_image:
    build:
      path: "{{ um_location }}"
      pull: false
    name: ugly-map
    tag: latest
    source: build

- name: Start container
  docker_container:
    name: ugly-map
    image: ugly-map
    hostname: ugly-map
    recreate: true
    state: started
    command: npm start
    exposed_ports:
      "{{ um_node_listening_port }}"
  changed_when: false
